package GUI;
/**
 * Enumeração dos tipos primitivos
 */
public enum TiposPrimitivos
{
    PONTOS, RETAS, CIRCULOS, RETANGULO, POLIGONO, COR, LINHAPOLIGONAL, CUBO, CARREGAR, SELECIONAR, TRANSLACAO, ROTACAO, APAGAR, SALVAR, LER, NENHUM 
}
